version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: timurkash/grpc-web-example-frontend
    env_file:
      - ./.env
    ports:
      - "3009:3000"
    networks:
      - test-backend

  envoy:
    build:
      context: envoy_time/envoy
      dockerfile: Dockerfile
    image: timurkash/grpc-web-example-envoy
    ports:
      - "8092:8080"
    depends_on:
      - time-server
    networks:
      - test-backend

  time-server:
    build:
      context: envoy_time/time
      dockerfile: Dockerfile
    image: timurkash/grpc-web-example-time
    env_file:
      - ./.env
#    ports:
#      - "9090:9090"
    networks:
      - test-backend

networks:
  test-backend:
