version: '3'

volumes:
  postgres_data:
      driver: local

services:
  envoy:
    build:
      context: ./envoytime/envoy
      dockerfile: Dockerfile
    image: timurkash/grpc-web-example-envoy
    ports:
      - "8091:8080"
    links:
      - time-server
    networks:
      - backend

  time-server:
    build:
      context: ./envoytime/time
      dockerfile: Dockerfile
    image: timurkash/grpc-web-example-time
    ports:
      - "9090:9090"
    networks:
      - backend

  postgres-keycloak:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - backend

  keycloak:
    image: jboss/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - "8080:8080"
    depends_on:
      - postgres-keycloak
    networks:
      - backend

networks:
  backend:
