version: '3'

volumes:
  postgres_data:
      driver: local

services:
  envoy:
    build:
      context: envoy_time/envoy
      dockerfile: Dockerfile
    image: timurkash/grpc-web-example-envoy
    ports:
      - "8092:8080"
    links:
      - time-server
    networks:
      - test-backend

  time-server:
    build:
      context: envoy_time/time
      dockerfile: Dockerfile
    image: timurkash/grpc-web-example-time
    environment:
      TEST: TIMUR
#    ports:
#      - "9090:9090"
    networks:
      - test-backend

networks:
  test-backend:
